export enum ActionType {
	LOADING_BOOK_LIST_START = 'LOADING_BOOK_LIST_START',
	LOADING_BOOK_LIST_SUCCESS = 'LOADING_BOOK_LIST_SUCCESS',
	LOADING_BOOK_LIST_FAIL = 'LOADING_BOOK_LIST_FAIL',

	LOADING_MUSIC_LIST_START = 'LOADING_MUSIC_LIST_START',
	LOADING_MUSIC_LIST_SUCCESS = 'LOADING_MUSIC_LIST_SUCCESS',
	LOADING_MUSIC_LIST_FAIL = 'LOADING_MUSIC_LIST_FAIL',

	LOADING_MOVIE_LIST_START = 'LOADING_MOVIE_LIST_START',
	LOADING_MOVIE_LIST_SUCCESS = 'LOADING_MOVIE_LIST_SUCCESS',
	LOADING_MOVIE_LIST_FAIL = 'LOADING_MOVIE_LIST_FAIL',

	SET_STACK_NAVIGATION = 'SET_STACK_NAVIGATION',
}
